eureka:
  instance:
    preferIpAddress: true  # * THE LINE WHICH FIXED A DAYLONG ERROR I HAD 🥹🥹🥹
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
name:
  value: chamika

spring:
  cloud:
    config:
      override-system-properties: false

# For ZipKin
management:
  tracing:
    sampling:
      probability: 1.0


