eureka:
  instance:
    hostname: eureka-server  # TODO: check this
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  cloud:
    config:
      override-system-properties: false

# For ZipKin
management:
  tracing:
    sampling:
      probability: 1.0


