spring:
  data:
    mongodb:
      username: chamika
      password: password
      host: mongo  # TODO: changed from localhost to mongo
      port: 27017
      database: notification
      authentication-database: admin

  kafka:
    consumer:

      bootstrap-servers: kafka:9092  # TODO: changed from localhost to kafka
      group-id: payment-group, order-group
      auto-offset-reset: earliest

      # since notification service is a consumer --> deserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.chamika.notification.kafka.payment, com.chamika.notification.kafka.order

        spring.json.type.mapping: paymentNotification:com.chamika.notification.kafka.payment.PaymentConfirmation, orderConfirmation:com.chamika.notification.kafka.order.OrderConfirmation

  mail:
    host: smtp.gmail.com  # TODO: change this to the actual mail server
    port: 465
    username: chamika.21@cse.mrt.ac.lk  # TODO: change this to the actual mail server username
    password: toqquqzbnvbmafdm  # TODO: change this to the actual mail server password

    # TODO: have to change the below properties later....
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
      protocol: smtp

server:
  port: 8040
