spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: chamika
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # since we are using flyway to manage the schema :)
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init product database"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers  # TODO: change this later after adding the api-gateway :)
    product-url: http://localhost:8050/api/v1/products  # TODO: change this later after adding the api-gateway :)

