spring:
  application:
    name: eureka # When we start the eureka server it will connect to the config server and get its configuration from eureka.yml file , so the correct naming is needed :)
  config:
    import: optional:configserver:http://localhost:8888  # This is the link for the config server

