services:

  postgres:
    container_name: psql_container_microservices_project
    image: postgres
    environment:
      POSTGRES_USER: chamika
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres_microservices_project:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices_project_network
    restart: unless-stopped


  mongo:
    container_name: mongo_microservices_project
    image: mongo
    volumes:
      - mongodb_microservices_project:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: chamika
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - microservices_project_network
    restart: unless-stopped


  mongo-express:
    container_name: mongo_express_microservices_project
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: chamika
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017

    networks:
      - microservices_project_network
    restart: unless-stopped

  mail-dev:
    container_name: maildev_microservices_project
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_microservices_project
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:22181"
    networks:
      - microservices_project_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - microservices_project_network
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092






networks:
  microservices_project_network:
    driver: bridge

volumes:
  postgres_microservices_project:
  mongodb_microservices_project: